apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      containers:
      - name: agent-service
        image: registry.digitalocean.com/moonregistry/agent-service:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "mysql+pymysql://admin:root0811@mooninsurance-mysql.cn4e2eau6isn.ap-south-1.rds.amazonaws.com:3306/mooninsurance"
        imagePullSecrets:
        - name: do-secret
