apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
      version: green
  template:
    metadata:
      labels:
        app: integration-service
        version: green

    spec:
      containers:
      - name: integration-service
        image: registry.digitalocean.com/moonregistry/integration-service:green
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: do-secret

---
apiVersion: v1
kind: Service
metadata:
  name: integration-service-green
spec:
  selector:
    app: integration-service
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: ClusterIP